### ISSUE TITLE
Swagger

### ISSUE THREAD

**Issue by pdonorio** [EUDAT-B2STAGE/http-api-base#1]
Provide an automatic configuration file to follow the [swagger](http://swagger.io/) protocol.

**Comment by pdonorio** [comment]
This could lead up to some hosting documentation such as, for example http://api-docs.io/

**Comment by pdonorio** [comment]
@akrause2014 and @cjhak i created this task, that you may use to investigate on this further

**Comment by cjhak** [comment]
@akrause2014; @pdonorio Thanks, taken, I'll look into it later this week.

**Comment by noumar** [comment]
@pdonorio, @akrause2014 or @muccix: Have any of you started on this? I would me interested in using or creating the spec in Swagger.

**Comment by pdonorio** [comment]
@noumar I don't think we really ever had the chance to start on this. 

Your contribution is very welcome, as Swagger can lead an important role in exposing our resources. If that's the case you may sync with @millingw which should have already dealt with the tool in his personal prototype.

**Comment by pdonorio** [comment]
Following @noumar prototype presented at the recent meeting in Bologna I decided this morning to give swagger in Python a shot.

After a quick look at [the list of swagger extensions in various language](http://swagger.io/open-source-integrations/) I landed into [flask-swagger](https://github.com/gangverk/flask-swagger). I also took a look into the code because it looks pretty small, and it might become a base for something similar into our code.

With this extensions you may write swagger documentation in `YAML` format. It can be done either [inside the `docstring` of a method](https://github.com/EUDAT-B2STAGE/http-api-base/blob/master/restapi/resources/endpoints.py#L33-L41) or as a [separated file](https://github.com/EUDAT-B2STAGE/http-api-base/blob/master/restapi/swagger/login/post.yaml). I tested both while on the train and it works just fine with our Flask-Restful behaviour. I saved [inside the repo](https://github.com/EUDAT-B2STAGE/http-api-base/blob/master/restapi/swagger/current_specs/spec.json) the produced JSON, which is served from an endpoint. At the moment I've set `/api/spec`.

The definition can be edited and validated inside the [swagger editor](http://editor.swagger.io/#/). It could also be served with the [API docs website](https://api-docs.io/). The swagger ui can be used [online](http://petstore.swagger.io/) or locally in debug mode with the [new docker image](https://hub.docker.com/r/eudatb2stage/swagger-ui/~/dockerfile/) I've built with nginx and the web code of the ui.

Finally, to learn more about what and how to write I already have found [a great tutorial](https://apihandyman.io/writing-openapi-swagger-specification-tutorial-part-1-introduction/).

All of this open up to some potential fixes:
- Read swagger specifications to link classes to endpoints
- Use the specifications to specify also parameters inside endpoints
- Create a directory dedicated to Swagger files, base and custom
- Read specifications at `unittest` time to automatically call with example parameters and test the defined output
- [create](https://github.com/apiaryio/dredd) an agnostic unittest based on swagger
- and, of course, let the users test the alpha with the Swagger UI

**Comment by pdonorio** [comment]
Note: **client generation** and **validation** are operations that swagger can apply with command line commands too

```bash

# CLIENT GENERATOR

curl  \
  -H "Content-type: application/json" \
  -X POST \
  -d '{"options": {"packageName": "b2stage_httpapi"},"swaggerUrl": "http://petstore.swagger.io/v2/swagger.json"}'  \
  https://generator.swagger.io/api/gen/clients/python

# VALIDATION

 http://online.swagger.io/validator/debug?url=http://petstore.swagger.io/v2/swagger.json
```
