### ISSUE TITLE
A structure to make services pluggable

### ISSUE THREAD

**Issue by pdonorio** [EUDAT-B2STAGE/http-api-base#14]
It all started with a simple "detect.py" file.

I think we can make it better, now.

**Comment by pdonorio** [comment]
So if @mdantonio will test this new structure on restangulask, we can close.

Actions needed:
- [x] login required is a method inside the `auth` module
- [x] remove references to the old decorator to recover auth, if any was used
- [x] start getting irods istances [like this](https://github.com/EUDAT-B2STAGE/http-api/blob/master/vanilla/apis/eudat.py#L123)

Let me know

**Comment by pdonorio** [comment]
It looks like the current irods instances need some overriding.

In fact we need to specify the user when getting the instance!

**Comment by mdantonio** [comment]
I tested the new structure on restangulask, but at the moment detect.py is able to discover the irods service only if started in an irods container... how to generalize to use a "real" irods instance?

**Comment by pdonorio** [comment]
I see you're testing another detect method.

Let me know if it works

**Comment by mdantonio** [comment]
I confirm that the changes committed with 51a6b16 solve the problem. Now detect.py is able to discover irods services from both irods containers and "real instances" (i.e. CINECA irods service)

**Comment by pdonorio** [comment]
We can close here then.

Next step is certificates for iRODS, see EUDAT-B2STAGE/http-api#3
