### ISSUE TITLE
A generic Models handler

### ISSUE THREAD

**Issue by pdonorio** [EUDAT-B2STAGE/http-api-base#16]
We need models for each plugged service (irods, graphdb, sqlalchemy, etc.).

There should be two models:
1. Base models. They implement authentication minimum requirements.
2. Custom models. If they exist, they can add base models or override existing ones.

**Comment by pdonorio** [comment]
Base models directory should be `commons/models/SERVICE_NAME.py`, while custom should lie in `vanilla/models`.

If one custom model has the same name of a base model, it must be accepted only if we verify with Meta Python that the custom class is a child of the base class.

**Comment by pdonorio** [comment]
Note, this can be done with 

``` python
issubclass(Child, Parent)
```

**Comment by pdonorio** [comment]
Models have been implemented inside the two directories.

The name of the service is very important!

**Comment by mdantonio** [comment]
It works very fine

The issue can be closed

**Comment by pdonorio** [comment]
Also EUDAT is passing the tests now:
https://travis-ci.org/EUDAT-B2STAGE/http-api/builds/135804883
