### ISSUE TITLE
Generalization of irods HTTP API

### ISSUE THREAD

**Issue by mdantonio** [EUDAT-B2STAGE/http-api-base#2]
I tried to connect irods HTTP API to CINECA irods server and I found some issues:
- authentication scheme is fixed (irods authenticaton). Required: PAM
  `irods_environment.json => "irods_authentication_scheme": "PAM"`
- PAM authentication also requires che chain.pem to validate the PAM CAT

```
export irodsSSLCACertificateFile=$HOME/chain.pem
export irodsSSLVerifyServer=cert
```
- cwd is fixed ({zone}/home/{user}). Required: custom
  `({zone}/home/{DRES}/{user})`
- cannot authenticate the admin account via GSI. This option could be useful to avoid to put the password in the docker-composer file

To achieve GSI-based admin auth:
- ICAT_1_ENV_IRODS_PASS should be removed (now is mandatory)
- X509_CERT_DIR / X509_USER_CERT / X509_USER_KEY should be set as soon as possibile (currently are not set at server start)

**Comment by pdonorio** [comment]
We'd go with `GSI` first, as it's the one really needed.
After that we will consider `PAM`.

**Comment by pdonorio** [comment]
Modification were made. 
I will make a pull request and you can test it.

**Comment by mdantonio** [comment]
GSI and custom homes now work fine

**Comment by pdonorio** [comment]
Great. What is missing now, but not very urgent, is a better PAM option.

[This](https://github.com/EUDAT-B2STAGE/http-api-base/blob/master/restapi/resources/services/irodsclient.py#L183) is the code where i should start.

On hold for now.

**Comment by pdonorio** [comment]
We are going to leave icommands. 
Authentication methods will be related to this repo:
https://github.com/EUDAT-B2STAGE/python-irodsclient

**Comment by mdantonio** [comment]
This issue can be closed since we are waiting for the integration with python-irodsclient
