### ISSUE TITLE
Let the developers write their custom response

### ISSUE THREAD

**Issue by pdonorio** [EUDAT-B2STAGE/http-api-base#23]
We should let the developer choose between:
- Original Flask response (with jsonify)
- Our base response (Meta + Response, see #7)
- His own custom response

**Comment by pdonorio** [comment]
Some of the logic should be moved out of `base.ExtendedApiResource.response`,
possibly inside `decorators.apimethod`.

Note: a requirement would be that the user defined custom response must be a Flask Response.

**Comment by pdonorio** [comment]
Used a different approach here f110d7daa69a9cc0273c0914d62458e7a2f9e260

Basically I am keeping the `response` method with a deprecation warning.

Instructions for writing the new response:
- directly send your data with `return`
- hijack the output by putting the element `{'specified_content': something, ...}`
- force the response (e.g. with errors) with the method `return self.force_response(**yourargs)`

**Comment by pdonorio** [comment]
Once we have checked that everything is fine I will remove the `response` method and close the issue. 

@mdantonio knock the door from your side when you're done

**Comment by mdantonio** [comment]
I found and corrected a couple of `self.response` in the Tokens endpoints (5c99b21cae361ef6846f388e76dc9b9c2cd1a9ce)

Modified the Foo endpoints

Modified my endpoints

Tested everything from my side -> deprecated response can be removed for me

P.S. uploader.py is still using self.response... i don't know if you use this... in case you have to fix it

**Comment by pdonorio** [comment]
Example for writing a custom response:

``` python
#####################################
# Make a custom response

# OPTION 1

@decorate.custom_response
def fedapp_response(
        defined_content=None,
        code=None,
        errors={},
        headers={}):

    return ExtendedApiResource.flask_response("Hello")

# OPTION 2

class Response(ExtendedApiResource):
    def fedapp_response(self, *args, **kwargs):
        return self.flask_response("Hello")

decorate.custom_response(Response().fedapp_response)
```

**Comment by pdonorio** [comment]
If I run my base tests with a custom response, we get the error:

``` bash
ERROR: test_02_get_login (test.base.test_restapi.TestRestAPI)
Check that you can login and receive back your token
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/code/test/base/test_restapi.py", line 108, in test_02_get_login
    'Authorization': 'Bearer ' + content['Response']['data']['token']}
KeyError: 'Response'
```

Base tests should get the information on how to find the token with a custom_response

**Comment by pdonorio** [comment]
We could write a system endpoint which shows the Schema of the response.

In that way tests could verify how the content is

**Comment by pdonorio** [comment]
@mdantonio do we have a separated issue to map the Schema (automatic) reply?

ExtendedApiResources class should provide inside the `__init__` constructor a way to map automatically /api/schemas/myendpoint response to the schema if `self._schema` is defined.

**Comment by mdantonio** [comment]
> do we have a separated issue to map the Schema (automatic) reply?

No, we have not

Note: now I have the schema definition stored in the data model (coupled with the lists _fields_to_show and _relationships_to_follow)

**Comment by pdonorio** [comment]
> > do we have a separated issue to map the Schema (automatic) reply?
> 
> No, we have not

We could refer to this other issue: https://github.com/pdonorio/restapi-template/issues/2

> Note: now I have the schema definition stored in the data model (coupled with the lists _fields_to_show and _relationships_to_follow)

But this is not going to be the final behavior. That definition should be based on the Class properties, even though we should let the developer write some customization (maybe in the way you already do you definition now)

**Comment by muccix** [comment]
I would start with a minimal set of keys, following this [specification](http://jsonapi.org/format/).
I'm not sure whether the parent entity should go under "link" or "relationships"..

For example, a GET request to an individual entity could return:

``` json
HTTP/1.1 200 OK
Content-Type: application/vnd.api+json

{
  "links": {
    "self": "https://be2safexx.eudat.eu/api/registered/path/to/directory/filename"
  },
  "meta": {
    "checksum": "BCA5BBE9FD2FDB94963C5D303418CB87",
    "creationTime": "Wed Oct 26 15:01:41 CEST 2016"
  },
  "data": {
    "type": "entity",
    "id": "path/to/directory/filename",
    },
    "relationships": {
      "parent": {
        "links": {
          "self": "https://be2safexx.eudat.eu/api/registered/path/to/directory"
        }
      }
    }
  }
```

A GET request to a collection could return:

``` json
HTTP/1.1 200 OK Content-Type: application/vnd.api+json

{
  "links": {
    "self": "https://be2safexx.eudat.eu/api/registered/path/to/directory"
  },
 "meta": {
    "checksum": "BCA5BBE9FD2FDB94963C5D303418CB87",
    "creationTime": "Wed Oct 26 15:01:41 CEST 2016"
  },
  "data": [{
    "type": "entity",
    "id": "path/to/directory/file1",
  }, {
    "type": "entity",
    "id": "path/to/directory/file2",
    }
  }]
}
```

For an empty collection:

``` json
{
  "links": {
    "self": "https://be2safexx.eudat.eu/api/registered/path/to/emptyDirectory"
  },
 "meta": {
    "checksum": "BCA5BBE9FD2FDB94963C5D303418CB87",
    "creationTime": "Wed Oct 26 15:01:41 CEST 2016"
  },
  "data": []
}
```

**Comment by pdonorio** [comment]
A key decision made today (reflecting on the entire base for HTTP API) is that: 
- A custom response should only change *_the content of *the internal response_ **. 
- Error(s) must be in the form of **a list of dictionaries**.

We want to make sure that in our framework we have a reasonable and flexible response. The structure of that response is:

``` json
{
 "Response": {
  "data": ANYTHING_HERE,
  "errors": [ {"FIELD": "message"}, {"ANOTHER_ERROR": "another message"}]
 },
 "Meta": {
    "data_type": "<class 'dict'>",
    "elements": 1,
    "errors": 1,
    "status": 200
 }
}
```

This was tested with curl, http + jq, javascript ui. It has all that is needed to make automatic parsing of any situation.
- All responses in all forks of this project must reflect the base above, no exceptions
- Tests will be able (with internal methods) to read the above response to separate the content and errors
- Calls to internal method that split the response should be cached within the same request, so that the computation is only applied once

**Comment by pdonorio** [comment]
The code which covers actions on endpoints response has become a little mess by adding little modifications in sparse packages.

I am trying to refactor, clean and things simpler by using a class Response which extends the original Flask class.

**Comment by pdonorio** [comment]
Made big changes here.
To @muccix and @mdantonio if you want to make thing works you have to:
- pull the api-base master
- update the docker images
- restart all

**Comment by pdonorio** [comment]
- [ ] Test again writing a custom response (e.g fedapp)
- [ ] Write a `custom_split` for custom content. Maybe not necessary.

**Comment by pdonorio** [comment]
Not important for production
