### ISSUE TITLE
Support for "normal" non-dockerized execution.

### ISSUE THREAD

**Issue by cookie33** [EUDAT-B2STAGE/http-api-base#26]
Hi,

If we are ever going to run the http-api it needs to be a standard product without docker and supporting python v2.6.

There is no installation document to do so.

How can we do this?

Greetings,

Robert Verkerk

**Comment by pdonorio** [comment]
Hi Robert, thanks for your interest in this project.

We have already #18 dedicated on Supporting Python 2 in the near future, although `2.6` is quite old, and probably we will focus on `2.7+`. 

We have to release our first beta for the end of September and so there will be no effort for that until the end of this year.

I will leave this issue open for writing the instructions for a non-dockerized launch of the project, which will consist in checking and describing how to create the environment variables that will detect the services, but once again not before the beta release.

**Comment by pdonorio** [comment]
A draft of what we should do for this feature:
- [ ] a separated command (`undockerized`?) inside the `do` script for launching without docker the flask server
- [ ] guided assistance for checking the environment variables step by step for every service, when `do` is launched with the previous option

**Comment by cookie33** [comment]
Hi,

We run Centos 6.8 and that has python 2.6. This will be supported till 2020. So please include python 2.6.

Greetings,

Robert Verkerk

**Comment by cookie33** [comment]
As a side note. Will it be an rpm on Centos? Or a deb on other distros? I don't like to do some magic commands in the background to install something. I like packages which are manageable.

**Comment by pdonorio** [comment]
> This will be supported till 2020. So please include python 2.6.

Python 2 is supported until 2020 [for version 2.7](https://hg.python.org/peps/rev/76d43e52d978), not 2.6 (for which the support has already ended). As already said we will cover the 2.7+ option as a first step; from there we may check if 2.6 can be a possibility with the effort we have.

> Will it be an rpm on Centos? Or a deb on other distros? 

I think we will build a `deb` package probably, but we don't have a clear decision at the moment, since it's still an early (alpha) stage.

**Comment by cookie33** [comment]
A deb package will not install on Centos. So we need an rpm.
