### ISSUE TITLE
Roles

### ISSUE THREAD

**Issue by pdonorio** [EUDAT-B2STAGE/http-api-base#29]
Authentication with roles (RBAC).

Implement a decorator for methods of a RESTful class that need to be accessed by a token issued only for accounts having all the roles specified.

**Comment by pdonorio** [comment]
A new method `roles_required` should be added to the `auth` mechanism to work as:

```
from auth import ROLE1, ROLE2

class MyEndpoint(ExtendedApiResource):

    @auth.roles_required(ROLE1, ROLE2, ...)
    @auth.login_required
    @decorate.apimethod
    def get(self, uuid=None):
         pass
```

It takes a list of constants which describes as names the set of minimum roles required for the `get` method of `MyEndpoint`.

The job of the method is to recall the main service authenticator, and for each role call the abstracted method that implements how to verify a single role in the current authentication service.

Note: we could also evaluate how `JWT` may help in this issue.

**Comment by pdonorio** [comment]
The method is created. I need to also add a few tests for this on the base test class.

**Comment by pdonorio** [comment]
Note, the correct order to make things work should be:

``` python
class MyEndpoint(ExtendedApiResource):

    @auth.login_required
    @auth.roles_required(ROLE1, ROLE2, ...)
    @decorate.apimethod
    def get(self, uuid=None):
         pass
```

This means that login_required has to be executed before roles_required or data will be missing

**Comment by pdonorio** [comment]
A simpler option could be to merge login_required and roles_required as a single method.

e.g.

``` python
from ...base import ExtendedApiResource
from ...auth import auth as authentication
from ...confs import config

MYROLE = 'some_custom_role'


class RolesEndpoint(ExtendedApiResource):

    @authentication.authorization_required(roles=[config.ROLE_INTERNAL, MYROLE])
    @decorate.apimethod
    def get(self):
         pass


class NoRolesButLoggedRequiredEndpoint(ExtendedApiResource):

    @authentication.authorization_required
    @decorate.apimethod
    def get(self):
         pass

```

What about it @mdantonio ?

**Comment by pdonorio** [comment]
We are supporting **deprecation** for this issue.
The decorator for authenticated methods has changed.

After we have solved the change of calls like:

``` python
from ...auth import auth

    @auth.login_required
    def get(self):
```

into

``` python
from ...auth import authentication

    @authentication.authorization_required
    def get(self):
```

and then we may close this issue.

Note: tests have to be better discussed [here](https://github.com/EUDAT-B2STAGE/http-api-base/issues/20#issuecomment-243403005)

**Comment by pdonorio** [comment]
- Fixed in EUDAT from [this commit](https://github.com/EUDAT-B2STAGE/http-api/commit/9fd341244cb44827b8fab94e4e7a368f6c67556a)
- Fedapp doesn't use the authentication yet
- Missing @mdantonio 

...and then we can remove the deprecated method and close.

**Comment by mdantonio** [comment]
I updated my endpoints and also updated the foo endpoints on rapydo

> we can remove the deprecated method and close.

We can. However the deprecation method raised no warning. It is not important now, but the deprecation mechanism do not worked

**Comment by mdantonio** [comment]
The admin-only tokens endpoints should be upgraded with the application of roles and relative tests should be modified

**Comment by pdonorio** [comment]
> However the deprecation method raised no warning.

because someone forgot to `logger.warning` -.-
