### ISSUE TITLE
Missing icommands

### ISSUE THREAD

**Issue by mdantonio** [EUDAT-B2STAGE/http-api-base#3]
At the moment few icommands are implemented/available (ils and ipwd?)

My personal order of priority is:

Priority: max
- imkdir (with optional -p flag)
- irm (with optional -r and -f flags)
- icp (with optional -r, -f, -k, -K flags)

Priority: medium
- ichmod

Priority: low
- imcoll

Note:
to check the irods connection and user authentication you may try with the _imiscsvrinfo_ command (instead of the _ils_ as currently done)

**Comment by pdonorio** [comment]
> imkdir (with optional -p flag)

Done.

See [my example](https://github.com/EUDAT-B2STAGE/http-api/blob/80fcfdb5c59ea368b1647e376af0eb5bbc434949/vanilla/apis/eudat.py#L58)

**Comment by pdonorio** [comment]
> irm (with optional -r and -f flags)
> icp (with optional -r, -f, -k, -K flags)

I wrote them, can you test them?

**Comment by mdantonio** [comment]
Both work fine, thank you

**Comment by mdantonio** [comment]
size of a collection:

`iquest "select sum(DATA_SIZE) where COLL_NAME like '/zone/home/abs_path/%'"`

output in bytes:

`DATA_SIZE = 55339104619`

It could be implemented as utility function

**Comment by mdantonio** [comment]
iuserinfo can be another utility command, to be used to verify the user existence before the execution of irods command

```
> iuserinfo existing_user
name: existing_user
id: 12345
type: rodsuser
zone: yourZone
info:
comment:
create time: 01430390342: 2015-04-30.12:39:02
modify time: 01430390342: 2015-04-30.12:39:02
GSI DN or Kerberos Principal Name: ...DN...
member of group: your group1
member of group: your group2
member of group: your groupN
```

```
> iuserinfo NOT_existing_user
User NOT_existing_user does not exist.

```

**Comment by pdonorio** [comment]
This one here is going to be deprecated, switching to the official python client is on the roadmap.

This should be closed and a new issue dedicated to the python driver implementation should start instead.

**Comment by pdonorio** [comment]
We now use prc.
