### ISSUE TITLE
Streaming upload in Flask

### ISSUE THREAD

**Issue by muccix** [EUDAT-B2STAGE/http-api-base#35]
Replacing icommands with the irods-python client will allow us to stream data from the http-api server to irods.

With respect to the transfer from the user to the http-api server it should be possible as well since “Werkzeug's documentation mentions the request.stream property”: see [here](http://blog.pelicandd.com/article/80/streaming-input-and-output-in-flask) for an example

**Comment by pdonorio** [comment]
Implemented here:  https://github.com/EUDAT-B2STAGE/http-api/issues/71
