### ISSUE TITLE
Use the correct status code

### ISSUE THREAD

**Issue by pdonorio** [EUDAT-B2STAGE/http-api-base#4]
Read here to understand the real meaning of the HTTP status code:

http://www.restapitutorial.com/httpstatuscodes.html

**Comment by mdantonio** [comment]
Now unexcepted errors return 400 Bad Request, should be changed to 500 Internal Server Error

400 should be used for invalid requests (missing data, validation errors, etc) after a verification

500 should be used when server skips to make verifications

This means that 500 errors should be avoided by implementing stronger verification procedures.
500 should be considered as a Segmentation Fault or NullPointerException

Now the server also uses 500 during the normal workflow, this is wrong and should be fixed (e.g. in uploader)

**Comment by mdantonio** [comment]
Use of 401 VS 403 VS 404

```
401 Unauthorized
403 Forbidden
404 Not Found
```

401 =  user authentication is missing. It informs user to expose credentials or token before to make this request again

403 = the user lacks the level of authorization required to access a resource (e.g. a user trying to access to an admin resource or a user trying to access to another user resource)

404 = the resource cannot be found. This means that the resource does not exist OR the user does not have the permission to see the resource (i.e. the resource is forbidden to the user)

So when to use 403 and when 404?
403 gives to the user an information: the resource exists but you cannot access to it
404 hides this information and can be preferable for security issues

This difference is also explained here:
https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.4

> 10.4.4 403 Forbidden
> [...] If the server does not wish to make this information available to the client, the status code 404 (Not Found) can be used instead.

**Comment by pdonorio** [comment]
Should we provide wrappers for these error codes?

Or should we act based on the type of error in an automatic way?

Inside the common dir of course

**Comment by mdantonio** [comment]
Why not

I adopted the following status codes:
- 200 OK
- 204 NO CONTENT
- 400 BAD REQUEST
- 401 UNAUTHORIZED
- 403 FORBIDDEN
- 404 NOT FOUND
- 405 METHOD_NOT_ALLOWED
- 409 CONFLICT
- 500 SERVER ERROR
