### ISSUE TITLE
Automatic letsencrypt certificate

### ISSUE THREAD

**Issue by pdonorio** [EUDAT-B2STAGE/http-api-base#40]
- Startup 
- Renewal

**Comment by pdonorio** [comment]
We have b2stage api certificate about to expire in a week.
That can be a good way to refresh our knowledge on how to start up and how to renew the cert.

The operation can be integrated inside the production compose right after.

**Comment by pdonorio** [comment]
Interesting reading [here](https://manas.tech/blog/2016/01/25/letsencrypt-certificate-auto-renewal-in-docker-powered-nginx-reverse-proxy.html)

**Comment by pdonorio** [comment]
It seems that `letsencrypt` is completely handled by [caddy](https://caddyserver.com/) web server, just for the record

**Comment by pdonorio** [comment]
Since `nginx` [can't have access to Environment variables](https://docs.apitools.com/blog/2014/07/02/using-environment-variables-in-nginx-conf.html) which pretty *sucks* for us with our docker-compose specifications, I really wonder if we should move to another proxy. Sigh. ha-proxy and caddy are among possible choices. 

A possible workaround is [to write a bash script that launches at startup](http://serverfault.com/a/827460) which modifies some key points of the file. Moving away from nginx we may lose the configuration we have reached so far.

**Comment by pdonorio** [comment]
A nice tutorial for automation inside this issue:
https://community.letsencrypt.org/t/howto-easy-cert-generation-and-renewal-with-nginx/3491

Also found this useful script which works pretty well:
https://github.com/Neilpang/acme.sh

Just in case, a good alternative:
https://github.com/lukas2511/dehydrated

I stored my tests with acme.sh and will make that the base to close this issue.

**Comment by pdonorio** [comment]
Things to fix in the eudat prototype:

- [x] remove prefixing into docker-compose files and use `cprefix` inside `do`
- [x] fix self signed certificate
- [x] `do` can launch renewall of letsencrypt certificate in production

**Comment by pdonorio** [comment]
> fix self signed certificate: do it from inside the nginx proxy container, and save it on the awaited place of the real certificates

When the certificate does not exist, the first time, nginx cannot be launched on 443. 

The workaround is to use the script for self signing a certificate if not existing at startup time. Then the automatic script I provided already works!

**Comment by pdonorio** [comment]
Tested with Mattia, there is still a bug for the script that does not copy certificates obtained since the path is wrong.

**Comment by pdonorio** [comment]
Depends on mdantonio/rapydo#7 completion

**Comment by mdantonio** [comment]
Consider to add the generation of Diffie Hellman parameters

in rapydo containers/frontend.yaml already mount a volume in /etc/nginx/ssl/

Add this in the init (Beware: it will take a very long time):

`openssl dhparam -out /etc/nginx/ssl/dhparam.pem 4096`

Add this to the proxy configuration:

`ssl_dhparam /etc/nginx/ssl/dhparam.pem;`

**Comment by pdonorio** [comment]
Should look how to add the email to the script. With that you receive a notification by letsencrypt to update the certificate :)

**Comment by pdonorio** [comment]
Created instructions to be tested with the eudat `do` command:

```

vim .env
# modify PROJECT_DOMAIN and LETSENCRYPT_MODE

./do PRODUCTION
# ssl is automatically created and self signed

./do check_certificate
# will show that it's self signed

./do letsencrypt
# launch ACME script and create certificates, also reload nginx

./do check_certificate
# should show what we like :)
```

I will try this today on our b2stage prototype.

> Consider to add the generation of Diffie Hellman parameters

I'm worried about the long time init.
We may discuss it for the next release.

**Comment by pdonorio** [comment]
> I will try this today on our b2stage prototype.

I tested it in 5 minutes, it works!
This is actually so cool I can't believe it my self...!
