### ISSUE TITLE
Check on certificate validity

### ISSUE THREAD

**Issue by muccix** [EUDAT-B2STAGE/http-api-base#45]
The function "check_certificate_validity" seems not to work correctly, responding the certificate is expired even if it is valid:

```bash
Executing command /usr/bin/openssl ['x509', '-in', '/opt/certificates/rodsminer/usercert.pem', '-text']
2017-03-14 09:38:58,282 DEBUG @restapi.resources.services.irods.client *GSI certificate (rodsminer) is expired on 2018-03-14 09:14:18+00:00*
```

**Comment by mdantonio** [comment]
The validity check is performed against both not_before and not_after dates but the message only refers to the not_after and should be fixed to be more accurate.

However could you confirm that the not_before date of this certificate is rightly set in the past?

You can get such information with something like this:

`openssl x509 -in yourcertificate.pem -text | grep -A 2 Validity`

**Comment by mdantonio** [comment]
In the meanwhile i modified the raised error for invalid certificates (pushed in the last_refactor branch)

**Comment by muccix** [comment]
$ openssl x509 -in /opt/certificates/rodsminer/usercert.pem -text | grep -A 2 Validity
        Validity
            Not Before: Mar 14 09:14:18 2017 GMT
            Not After : Mar 14 09:14:18 2018 GMT

When we got the error, we checked the date:

$ date
Tue Mar 14 09:48:34 UTC 2017

**Comment by mdantonio** [comment]
I modified the `check_certificate_validity` function and now it should works

A delay of 1 hour was applied to both before and after dates, so that the certificate was not valid until Mar 14 10:14:18 2017 GMT ... I fixed this validity check and how such delay is only applied on the after date
