### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by pdonorio** [EUDAT-B2STAGE/http-api-base#5]
Finally we go with testing. 

`Nose` will be the chosen library.
- [x] Learn how to make tests with Flask 
- [x] then let the user specify custom test on endpoints
- [x]  adding coverage
- [x] documentation for tests and coverage?
- [x] move tests under the http-api repo (in vanilla folder)

**Comment by pdonorio** [comment]
Note: add to docker image the nose library

**Comment by pdonorio** [comment]
To run a docker container to make tests:

`docker run -it -v (pwd):/tmp -h apitest -u root eudatb2safe/apiserver bash`

(even if it's just to verify)

**Comment by pdonorio** [comment]
> Note: add to docker image the nose library

Updated the image, it should be available in an hour.

**Comment by muccix** [comment]
Problem 1: how can I remove automatically the files upload in order to repeat the test (overwrite is not allowed..)?

Problem 2: nosetests does not accept parameters 

$ nosetests --nocapture
usage: nosetests [-h] [--no-security] [--debug] [--remove-old]
nosetests: error: unrecognized arguments: --nocapture

**Comment by pdonorio** [comment]
> Problem 1: how can I remove automatically the files upload in order to repeat the test (overwrite is not allowed..)?

I just implemented the delete method to solve this problem.

I tested it with:

``` bash
http DELETE HOST:PORT/api/dataobjects/DATAOBJECT?collection=PATH/TO/DATAOBJECT
```

Let me know if it works.

> Problem 2: nosetests does not accept parameters

I see that the other help works:

``` bash
$ nosetests --help | grep noca
  -s, --nocapture       Don't capture stdout (any stdout output will be
```

I fear that nose uses `argparse` to handle cli parameters. I am also using the same library with this project, therefore i guess there is an overwriting of nose parameters.
I need to investigate on how to avoid this.

**Comment by muccix** [comment]
@pdonorio in the response to "GET /api/collections" why each element inside "data" is a list with only 1 element?

`"data": [
        [
            "/tempZone/home/guest:"
        ], 
        [
            "test200MB.img"
        ], 
        [
            "testa.zip"
        ], 
        [
            "test_light1.pdf"
        ], 
        [
            "test_light2.pdf"
        ], 
        [
            "test_light3.pdf"
        ], 
        [
            "test_light4.pdf"
        ], 
        [
            "test_light5.pdf"
        ], 
        [
            "test.zip"
        ]
    ], 
`

**Comment by pdonorio** [comment]
> why each element inside "data" is a list with only 1 element?

Because there is no official parser inside the code to get the iRODS output right :wink: 

I think @mdantonio is working on one, that we may integrate when i come back (in 2 weeks).

**Comment by muccix** [comment]
What about adding badges to show the status of the unit tests? Travis (https://travis-ci.org/ and https://github.com/integrations/travis-ci)  seems to be promising..

**Comment by pdonorio** [comment]
I am positive with Travis.
Did you try it yet?

**Comment by akrause2014** [comment]
Travis is really good. I've used it on another project: [https://github.com/dispel4py/dispel4py](url) Might be worth looking at the setup for the Python environment. I haven't used it with Docker though but it has built-in support for that.

**Comment by muccix** [comment]
OK. I will have a look at it!

**Comment by muccix** [comment]
@mdantonio how can I update the submodule "backend" to the latest commit in the http-api repo?

**Comment by mdantonio** [comment]
From the main repo this should work:

```
    git submodule sync
    git submodule update
```

(sometimes "git submodule update" is needed twice for unknown reasons)

When the sync_and_update don't work you can proceed with a simple pull from the backend repo but in this case you will detach the main repo and a re-attachment is then required.

However, the submodule mechanism is so issues-prone that now in the Telethon repo i'm no longer using submodules. I added backend as normal external repository. We should discuss about the two alternative solutions to decide our preferred one

**Comment by muccix** [comment]
Thanks @mdantonio, but I'm not sure it worked for me:

```
$ git submodule sync
Synchronizing submodule url for 'backend'
rmucci00@nrmucci000203272:~/Devel/EUDAT/http-api$ git submodule update
Submodule path 'backend': checked out 'd2713206a2daa205370be3699089e8ba4325d724'
rmucci00@nrmucci000203272:~/Devel/EUDAT/http-api$ git status
On branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working directory clean
```

The repo http-api is still linking an old versione of the http-api-base repo..

**Comment by mdantonio** [comment]
Ok, so the main repo is not synchronized
You have to follow the second way and cross your fingers :smile: 

```
cd backend
git pull origin master
cd ..
git commit backend -m "backend submodule update"
```

**Comment by pdonorio** [comment]
Ok. So far we clearly understood that submodules is the official way of having another repository inside your repo, but honestly it is a complicated tool if you want to also modify the submodule (create branches, let other users modify it, etc.).

So, as @mdantonio said, we are going to stop using it soon. VERY SOON.

In the meantime, @muccix can "test the tests" with:

``` bash
git clone https://github.com/EUDAT-B2STAGE/http-api.git
cd http-api
rm -rf backend
git clone https://github.com/EUDAT-B2STAGE/http-api-base.git backend
```

You should be good to go like that, let me know.
Of couse, do not commit modifications on "backend" in the main http-api repo.

**Comment by mdantonio** [comment]
> rm -rf backend

For some quick test this will be ok, but to completely remove a submodule from a repository, some more steps are required

The official guide for submodule removal: https://git.wiki.kernel.org/index.php/GitSubmoduleTutorial#Removal

Here a more extensive how-to from stackoverflow:
http://stackoverflow.com/questions/1260748/how-do-i-remove-a-submodule
1. Delete the relevant section from the `.gitmodules` file.
2. Stage the `.gitmodules` changes `git add .gitmodules`
3. Delete the relevant section from `.git/config`.
4. Run `git rm --cached path_to_submodule` (no trailing slash).
5. Run `rm -rf .git/modules/path_to_submodule`
6. Commit `git commit -m "Removed submodule <name>"`
7. Delete the now untracked submodule files `rm -rf path_to_submodule`

This should work with any git version (>=1.5.3). Some git versions may have a `git submodule deinit` command, but i don't tried it

**Comment by muccix** [comment]
Travis is served!

https://travis-ci.org/EUDAT-B2STAGE/http-api

**Comment by pdonorio** [comment]
> For some quick test this will be ok, but to completely remove a submodule from a repository, some more steps are required

I will probably open an issue to commit those changes inside the http-api repo.

> Travis is served!

Next step is coverage. Here is some great reading: 
http://www.saltycrane.com/blog/2012/04/test-coverage-nose-and-coveragepy/

Should we open a new issue? I think it should be easy.

**Comment by pdonorio** [comment]
I updated my personal python base image to include the nose+coverage package.

To update on a project where you already initialized the volumes:

``` bash
scripts/run.sh update
scripts/run.sh graceful
```

Since with `docker-compose 1.7+` we have the new `exec` command, at this point we may already do:

``` bash
docker-compose exec rest nosetests --cover-branches --with-coverage --cover-erase --cover-package=restapi --cover-html
```

This will output more details on single `restapi` module files. E.g. one line is:

``` bash
restapi/models.py                              55     16      0      0    71%   11-17, 43, 59-60, 63, 66, 69, 72, 75, 78
```

Telling you the coverage percentage and line not covered.
There is also a directory which shows inside HTML files in red lines of the code which are uncovered by the tests!

I think this might help (me) to remove some useless code before improving the tests.

So far we have:

``` bash
TOTAL                                        1245    425    272     55    61%
```

What is the good percentage to reach?

> If you TDD your code you should get a 90%+ coverage as a bonus. 

100% of course is not reachable in practice for many reasons.

We may read here and other resources to get better:
https://docs.python.org/devguide/coverage.html

**Comment by pdonorio** [comment]
@muccix we may add coverage to travis now.

Also what about some documentation to write tests?

**Comment by muccix** [comment]
@pdonorio Ok, I will go for that!

**Comment by pdonorio** [comment]
Added a new command to `run.sh`.

We may now:

``` bash
$ scripts/run.sh api_test

[...]

---------------------------------------------------------------------------------------
TOTAL                                        1245    425    272     55    61%
----------------------------------------------------------------------
Ran 6 tests in 8.054s

OK
```

**Comment by pdonorio** [comment]
Travis build fails due to permissions in creating the coverage statistics:

``` bash
PermissionError: [Errno 13] Permission denied: '/code/project/.coverage'
```

This is probably due to the fact that the code is mounted by root or the current user id on the host, which could be different from the 1000 id of the first user inside the docker container ("irods" user).

Need to investigate how to avoid it.

**Comment by pdonorio** [comment]
Fixed "permission denied" with [this commit](https://github.com/EUDAT-B2STAGE/http-api/commit/80709dac86bcb318890742bc24bb5fbc4738fc7f)

**Comment by pdonorio** [comment]
Useful extra parameters for nosetests:
- Launch all tests but exit if one fails

``` bash
nosetests --stop
```
- Launch only one test

``` bash
# pathToPythonFile:className.methodTest e.g.
nosetests test/test_dataobjects.py:TestDataObjects.test_06_post_already_existing_dataobjects
```

**Comment by pdonorio** [comment]
Note: we should only push commits with the `run.sh` scripts.

I will probably add a check that if tests fails push will be skipped

**Comment by muccix** [comment]
I have just realized that nose has been replaced by nose2 (https://nose2.readthedocs.io/en/latest/index.html).

I'm going to update the tests to make them work with nose2.

@pdonorio could you please add nose2 and cov-core ($ pip install cov-core) in the docker image?

**Comment by pdonorio** [comment]
I updated the API server image:

https://hub.docker.com/r/eudatb2safe/apiserver/builds/bifuftqlbmul2zkyhxrfjbh/

**Comment by pdonorio** [comment]
Worked with Mattia to fix the parser on irods errors longer than one line.
Tests should be updated.
