### ISSUE TITLE
Python3 command missing

### ISSUE THREAD

**Issue by TomZastrow** [EUDAT-B2STAGE/http-api-base#51]
When firing up the docker container with "docker-compose up", I got the error:

Starting eudatrest_rest_1
Attaching to eudatrest_rest_1
rest_1  | /usr/bin/env: 'python3': No such file or directory
eudatrest_rest_1 exited with code 127

-> starting the Docker container manually shows me that there is a command "python3.6" but not "python3" inside the container

**Comment by pdonorio** [comment]
Hello and welcome my friend.

This project is the core of our HTTP-API development at work. We didn't know of any external user so far; in fact the documentation is outdated. The code is also under refactor and will be moved with a new name into a new github namespace very soon.

The base/core is also not intended to be used alone, there should be a "vanilla" project to customize the base like the [EUDAT HTTP API](https://github.com/EUDAT-B2STAGE/http-api).

So to fix the problem there I can change the [python env](https://github.com/EUDAT-B2STAGE/http-api-base/blob/master/run.py#L1) to be just `python` but there would be other problems after.

Do you mind if I ask you how are you planning to use or test this project? We wanted to write a new documentation so it could be interesting to know where to focus at start.

**Comment by pdonorio** [comment]
Closing for missing feedback. Feel free to reopen. 

Note that we created a dedicated team for this project, this repo is deprecated: 
https://github.com/rapydo
