### ISSUE TITLE
As standard REST HTTP API response as we can get

### ISSUE THREAD

**Issue by pdonorio** [EUDAT-B2STAGE/http-api-base#7]
My first proposal

``` json
{
 "Response": {
  "data": ["if there is data"],
  "errors": [ {"FIELD": "message"}, {"ANOTHER_ERROR": "another message"}]
 },
 "Meta": {
    "data_type": "<class 'dict'>",
    "elements": 1,
    "errors": 1,
    "status": 500
 }
}
```

**Comment by pdonorio** [comment]
@mdantonio discussion is open

**Comment by mdantonio** [comment]
The check to verify if the content of the response contains data or error list should be based on status code?

if status = 2__:
     read Response.data

if status = 4__:
     read Response.errors

> "elements": 1

Elements only refers to data? Or can also refers to errors?
In the first case: it should be 0 because due to errors there is no data
In the second case: it should be 2 because your example reports 2 errors

Data and errors can be both defined? (in such case, errors can also be interpreted as something similar to warnings)

**Comment by pdonorio** [comment]
> The check to verify if the content of the response contains data or error list should be based on status code?

Yes. We're keeping track of the codes [here](https://github.com/EUDAT-B2STAGE/http-api-base/blob/master/restapi/htmlcodes.py). 

I think the check could be something like:

``` python
if status < 300:
    OK
else:
    POSSIBLE BLOCKING ERROR
```

We should do the same for JS.

> Elements only refers to data? Or can also refers to errors?

It should refer to both, for now it does not.

> Data and errors can be both defined?

If we wants fine grained warnings yes. It could be done.

**Comment by pdonorio** [comment]
Digging further i have seen that:
- 3xx is more a Warning, rather than an error.
- 4xx and 5xx is were we clearly have a problem.

As proposed from @mdantonio we could have the situation where there is both data and error inside `Response`, which is a warning.

@muccix this could be discussed now, we need it for implementing tests which can understand the server errors.

**Comment by pdonorio** [comment]
Implementation is to be applied at [this method](https://github.com/EUDAT-B2STAGE/http-api-base/blob/master/restapi/resources/base.py#L140)

**Comment by pdonorio** [comment]
Ok. This was implemented.

@muccix we can now use these standards for acting inside the tests, when checking if the response is right or the error is as supposed.

@mdantonio you can check this on the ui side too!

**Comment by pdonorio** [comment]
Close here. Please re-open if you find some issues.

**Comment by pdonorio** [comment]
Some bug fixes.

I added the 'error count' inside the meta section.

**Comment by pdonorio** [comment]
Found out you can [make a flask custom response](http://blog.miguelgrinberg.com/post/customizing-the-flask-response-class) as a  class which could be used to convert also flask original response (e.g. method not allowed) into the user provided JSON schema.

**Comment by pdonorio** [comment]
I wrote an [example](https://github.com/EUDAT-B2STAGE/http-api-base/blob/master/restapi/server.py#L59-L76) for this response, that could be activated [here](https://github.com/EUDAT-B2STAGE/http-api-base/blob/master/restapi/server.py#L167)

**Comment by pdonorio** [comment]
Resources to get the errors right with flask_restful:
1. [interesting post](http://www.wiredmonk.me/error-handling-and-logging-in-flask-restful.html)
2. [SO explain for exceptions](http://stackoverflow.com/a/32449070/2114395)

**Comment by pdonorio** [comment]
After latest changes to how response is made, the custom response example has to be refactored.
This will follow up in #23

**Comment by pdonorio** [comment]
The only thing missing in this issue is a parameter to disable the external wrapping of Meta and Response on request (and let the unittest know it).

**Comment by pdonorio** [comment]
Mostly implemented, no effort for more, now
