### ISSUE TITLE
Parse irods responses

### ISSUE THREAD

**Issue by pdonorio** [EUDAT-B2STAGE/http-api-base#9]
A parser for icommand outputs:
- [x] parse errors to limit only to the meaningful phrase/sentence
- [ ] parse normal output to json/dict

**Comment by mdantonio** [comment]
Just to document the crazy irods responses.
Some code errors are re-used in different contexts

`$ imkdir TEST`

`$ imkdir TEST`

> ERROR: mkdirUtil: mkColl of /.../TEST error. 
> status = -809000 CATALOG_ALREADY_HAS_ITEM_BY_THAT_NAME

`$ imeta add -C TEST test JustATest`

`$ imeta add -C TEST test JustATest`

> ERROR: rcModAVUMetadata failed with error -809000 CATALOG_ALREADY_HAS_ITEM_BY_THAT_NAME

**Comment by pdonorio** [comment]
We have some skeleton to parse errors.

Do we also parse the normal output? We have a little hurry about the `ils` command output. Could it be done by the end of the week?

**Comment by mdantonio** [comment]
`ils` output is already converted into a json by the [list_as_json](https://github.com/EUDAT-B2STAGE/http-api-base/blob/master/restapi/resources/services/irods/client.py#L496) function (the related commit is just few comments above in this issue)

**Comment by pdonorio** [comment]
What is missing then?

**Comment by mdantonio** [comment]
> What is missing then?

Mainly the following points:
- Verify that the implemented method works for you (it is implemented on the basis of my requirements and at now you never tested in your use case)
- Since the implemented method is quite rough, we should try to enhance it (also based on the previous point)
- This issue should cover other command outputs (now only ils is implemented)
- We should try to define some common utilities to parse outputs by generalizing what done for ils

**Comment by pdonorio** [comment]
> Verify that the implemented method works for you

I'll check that this week

> We should try to define some common utilities to parse outputs by generalizing what done for ils

And this you should/could do it soon. The sooner the better.

**Comment by pdonorio** [comment]
Note that the chances we will stop using icommands are quite good for the upcoming year. 

How would that impact on existing parsers?

**Comment by pdonorio** [comment]
ping

**Comment by mdantonio** [comment]
We don't have many parsers.

We have an "ils" and an "ils -A" parser and they are to be rewritten

We have a mechanism to parse errors and probabily we have to change it to adapt to Exceptions raised by the client

**Comment by pdonorio** [comment]
Ok so now this depends on EUDAT-B2STAGE/http-api#46

**Comment by pdonorio** [comment]
We now use prc
